# Generated by ariadne-codegen
# Source: ./graphql/schema.graphql

from enum import Enum


class EmoteSearchCategory(str, Enum):
    TOP = "TOP"
    TRENDING_DAY = "TRENDING_DAY"
    TRENDING_WEEK = "TRENDING_WEEK"
    TRENDING_MONTH = "TRENDING_MONTH"
    FEATURED = "FEATURED"
    NEW = "NEW"
    GLOBAL = "GLOBAL"


class EmoteSetName(str, Enum):
    GLOBAL = "GLOBAL"


class ListItemAction(str, Enum):
    ADD = "ADD"
    UPDATE = "UPDATE"
    REMOVE = "REMOVE"


class MessageKind(str, Enum):
    EMOTE_COMMENT = "EMOTE_COMMENT"
    MOD_REQUEST = "MOD_REQUEST"
    INBOX = "INBOX"
    NEWS = "NEWS"


class ReportStatus(str, Enum):
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    CLOSED = "CLOSED"


class SortOrder(str, Enum):
    ASCENDING = "ASCENDING"
    DESCENDING = "DESCENDING"


class SubscriptionPeriodKind(str, Enum):
    yearly = "yearly"
    monthly = "monthly"
