# Generated by ariadne-codegen
# Source: ./graphql/queries.graphql

from typing import Any, List

from .base_model import BaseModel


class SearchEmotes(BaseModel):
    emotes: "SearchEmotesEmotes"


class SearchEmotesEmotes(BaseModel):
    count: int
    items: List["SearchEmotesEmotesItems"]


class SearchEmotesEmotesItems(BaseModel):
    id: Any
    name: str
    host: "SearchEmotesEmotesItemsHost"


class SearchEmotesEmotesItemsHost(BaseModel):
    url: str
    files: List["SearchEmotesEmotesItemsHostFiles"]


class SearchEmotesEmotesItemsHostFiles(BaseModel):
    name: str
    width: int
    height: int
    format: Any


SearchEmotes.model_rebuild()
SearchEmotesEmotes.model_rebuild()
SearchEmotesEmotesItems.model_rebuild()
SearchEmotesEmotesItemsHost.model_rebuild()
