[project]
name = "back-end"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "ariadne-codegen>=0.14.0",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.0",
]

[project.scripts]
back_end = "back_end:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
